### ISSUE TITLE
Typo

### ISSUE THREAD

**Issue by dimadk24** [aleksei-bulgak-study/rsschool-codejam1-cv#2]
![image](https://user-images.githubusercontent.com/25607790/46579903-bf2e9500-ca22-11e8-91f8-6d8029bf3e57.png)

**Comment by aleksei-bulgak** [comment]
@DimaDK24 Thanks for your review

**Comment by aleksei-bulgak-study** [comment]
Fix: https://github.com/aleksei-bulgak-study/rsschool-codejam1-cv/pull/3
Will be merged after RSS team will accept task

**Comment by aleksei-bulgak-study** [comment]
https://github.com/aleksei-bulgak-study/rsschool-codejam1-cv/pull/3
